### ISSUE TITLE
When in Preview change mono-spaced font to Courier 12

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/Blender_Screenwriter#1]
In theory something like this should work on Windows: 

```
        # setting font (on Windows)
        try:
            for a in bpy.context.screen.areas:
                if a.type == 'PREFERENCES': 
                    bpy.context.area.type ="PREFERENCES"
                    bpy.context.preferences.view.font_path_ui_mono("C:\\Windows\\Fonts\\Courier.ttf")
                    break
        except RuntimeError as ex:
            error_report = "\n".join(ex.args)
            print("Caught error:", error_report)
            #pass
```

But it doesn't. On top of this, finding the right folders for installed fonts isn't a trivial matter on Mac and Linux... And do all OS have Courier pre-installed?

Or should Courier Prime be installed with the Screenwriter add-on?

**Comment by AndreaMonzini** [comment]
I think that Courier Prime should be the first choice if the License is compatible.
For example Courier Prime is used  in the following MIT licensed projects:

Better Fountain by  @piersdeseilligny 
https://github.com/piersdeseilligny/betterfountain/tree/master/src/courierprime

Writer by @HendrikNoeller
https://github.com/HendrikNoeller/Writer/tree/master/CourierPrime

**Comment by tin2tin** [comment]
Since imo it is not possible to install a font cross platform from the add-on, it makes no sense to try to use the add on to change the font to a font most people will not have installed. 

I know about Courier Prime, and screenplay formatting etc., since I've worked with screenplays as a writer, reader and feature film director for more than 20 years. But I think it is best to let the users change the font themselves, because I know of now possible way to access the Fonts folders cross platform. If you find a way to get the Fonts folders paths on all OS'es using Python let me know.  

If you want to help, maybe you could look into the fountain markups which currently aren't converted, by looking at fountain2pfd?

**Comment by AndreaMonzini** [comment]
I answered to your question "Or should Courier Prime be installed with the Screenwriter add-on?".
It's great that you are an experienced screenplay writer, good to know to avoid other screenplay references. I try to help with my skills ( very limited about programming ).

**Comment by tin2tin** [comment]
If anyone feels up for implementing it. Here's a link to some code which apparently should solve the problem: https://peippo.at/cross-platform-python-font-installer/
