### ISSUE TITLE
Asset linking for auto insertion into created sequence

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/Blender_Screenwriter#12]
Now that it is possible to create a sequence with generated scenes and added subtitles, additional greatness would be to assign 3d assets to elements in the script like characters, locations, props, lightning setups, camera setups etc.

I did a quick update of eLinker to 2.80, there are still a few things which needs to be updated, but the coder will take a look this weekend: 
![image](https://user-images.githubusercontent.com/1322593/68989542-a9f08080-0848-11ea-8b6f-3969dd007ba6.png)
https://github.com/EibrielInv/scripts

Maybe it could somehow be expanded to do the screenplay key element assigning and insertion?

**Comment by AndreaMonzini** [comment]
I was thinking about a library of Grease Pencil pre-made sketched assets ( characters, props, backgrounds, foregrounds) for quick storyboards.

> Maybe it could somehow be expanded to do the screenplay key element assigning and insertion?

Are you thinking about keywords, metadata ( key elements) to assign the assets automatically with the script ?

We could use the key elements inside the Fountain Boneyard to keep the Fountain compatibility:

https://fountain.io/syntax#section-bone

Maybe in future we can study procedural assets integrated with AI words recognition.
Or text to speech python modules ( pyttsx3, or in future Mozilla TTS ) to create audio speech assets.
I was evaluating the Timecode key to assign precisely in the timeline assets, cuts, camera, etc... 
In this way we can create ( optionally ) the animatic directly with a plain text, also accessible for people with visual impairment. ( a sort of markdown animation ! )

The possibility are indeed without limits.

**Comment by tin2tin** [comment]
In order to keep it doable, I think it should go with the creation of scenes, and stick to to words in the script. 

Some obvious words would be: 
WORD > OPTIONAL USE
Scene headings > Location and prop elements ex. house, street, office, gun, car... 
Character names > When a character speaks in a scene an optional character can be added to scene.
int. ext. > Light set up, practical vs. natural light sources auto added. 
day,  night > Light set up. Night sky. 
Custom > Characters without dialogue, animals etc. 

Though it would be nice to have some assets to play around with, it may be outside of this project to provide assets packs. 

At this time I think the ambition should be to give the users the option to have auto collected assets per scene as a sandbox, but the actual assets should the users collect and assign themselves.

**Comment by AndreaMonzini** [comment]
So like link the assets to the predefined words in the script ( in a an user definite database )
Asset 3D Lowpoly House----->  house, home, residence, building (SCENE word database )
EXT. Home Day
SCENE word database ---> house, **home**, residence, building ( database )---> 3D Lowpoly House

> Old post about community created asserts packs for previz: https://blenderartists.org/t/creating-a-collaborative-previz-assets-pack/700383

I was starting to draw super simple basic GP assets ( maybe useful for a test ) but lowpoly assets would be better ( you can easely change lights ).

![sketch](https://user-images.githubusercontent.com/12413409/68993711-6c591b00-087b-11ea-893d-34d395348e87.png)

**Comment by AndreaMonzini** [comment]
There is ta nice  CC0 licensed ( but nice to remember the attribute to IcySugar ) Lowpoly rigged Asset from Blend Swap :
https://www.blendswap.com/blend/21420

I imported it to 2.81, works well with EEVEE

![rigged_lowpoly](https://user-images.githubusercontent.com/12413409/68994346-4aaf6200-0882-11ea-9176-53aafe9ffc38.png)

**Comment by tin2tin** [comment]
If we limit the "assign assets to keywords" to objects in the current 3d scene(like the main scene containing the full sequence). A mock-up of the UI could look like this: 
![image](https://user-images.githubusercontent.com/1322593/69001256-9fcb9200-08db-11ea-8beb-193461fc63a4.png)

To the left, words from the screenplay can be added. When they are added, the list on the right is empty.

In order to populate the list on the right, the users will have to select a keyword and then select objects in the 3D View. In the mock-up the house(location) has been assigned window object, door object, sun object, camera object etc. 

So when pressing the "Create Sequence" button every scene called house(should have been INT. HOUSE), will get all the objects from the right list added automatically. And in every scene EDWARD is mentioned, the object(s) assigned to EDWARD will be added automatically. 

This could be expanded into file libs on hdd, like eLinker, but maybe this will be too complicated to code the first time around. 

(Btw. I forgot the remove buttons in the mock-up, And maybe there should be preset extraction and adding of Characters, Locations, Time of Day etc.)

**Comment by AndreaMonzini** [comment]
Ok, i think that this implementation is very useful to organize the scene from a precise script.
In this way we can assign one keyword ( or 1 string ) to multiple objects and it is super useful for a previz from the script.

I think it would be also useful to assign keywords to link external .blend files automatically for complex projects .
Could we also add multiple keywords to the same object ?
In this way the assignment could be more flexible and some keywords would be useful for different scripts ( or the same script if we use different words for similar objects ).

![mockup6](https://user-images.githubusercontent.com/12413409/69008962-d2fc3880-0950-11ea-8eb4-da4005c98a80.png)
 

Maybe  the future we also assign complex keyword groups ( AI based ) to a procedural node based assets.

**Comment by tin2tin** [comment]
On the UI part: https://blender.stackexchange.com/questions/158440/how-to-get-one-uilist-to-control-the-contents-of-another-uilist

**Comment by sirdavid32** [comment]
How far can we get into formatting? Is there a way to have a black background against white text (like close caption text) in the viewport?
I've read the SRT subtitle formats (they don't allow background color for characters).
So I figured, the text itself could be using a black background specifically (here's a .ttf example: https://www.1001fonts.com/color-basic-font.html)
And here's an application: https://imgur.com/gallery/Ycxt6Px
Currently, I am animating the visibility of the text object on every Marker to keep the timing consistent. But I know there can be a better way.

**Comment by tin2tin** [comment]
@sirdavid32 It's the wrong add-on you're writing about here. This one does not add text in the 3d view, and do not intent to. Watch the video on the main page to see what's going on here.

**Comment by tin2tin** [comment]
This has been implemented.
