### ISSUE TITLE
problem with preview

### ISSUE THREAD

**Issue by samytichadou** [tin2tin/Blender_Screenwriter#13]
Hi, i installed the addon on ubuntu 19.04 and tried with blender 2.82 (-e5b788bad8bc-linux-glibc217-x86_64)
I have hard times to get a preview working, i opened the fountain script you provided in the zip of the last release, but when clicking on any of the 3 operators, i don't get anything and it raises no error at all.
The preview operator do get me a "wrong way" cursor which disappears when clicking or hitting esc key.
I don't have a good knowledge of the addon so far, what should happend when working correctly ? splitting the text editor to get a preview windows when hitting preview is that right ?

**Comment by AndreaMonzini** [comment]
Hi, i use Linux too ( latest  Pop_OS distro )
Try to start new project from zero or eventually unlink the text data-block.
Check also please the addon folder if there are double installations.
Eventually delete the addon and reistall it.

**Comment by samytichadou** [comment]
Hi @AndreaMonzini thanks for your answer !
I'm using the 012 (from releases), no luck when reinstalling the addon, deleting pycache, starting with clean project so far.
No dupes in the addon folder (clean 2.82 version)
Just to be sure, the way to go is click on the preview button to get the split text editor isn't that right ? and then refresh it or enable live preview ? Or do i have to do a second text editor manually ? 

I just overviewed the code so far, not sure about it... thanks !

**Comment by AndreaMonzini** [comment]
> Just to be sure, the way to go is click on the preview button to get the split text editor isn't that right ? and then refresh it or enable live preview ?

Yes, the preview button with open a second text editor for a duel view and the preview.
If refresh to manually update the preview or use the live preview.

Anyway i will test the different versions to check if it works here.
If you download the last committed version as ZIP from Github, you should unzip it and re-zip without a parent folder.

**Comment by AndreaMonzini** [comment]
Just checked that the Release 012 and the last committed master work with 2.82.
I zipped the last master:

[Blender_Screenwriter-master.zip](https://github.com/tin2tin/Blender_Screenwriter/files/3854279/Blender_Screenwriter-master.zip)

**Comment by samytichadou** [comment]
No luck so far, but it seems the problem is related with this part of the dual screen operator
```
    if area == thisarea:
        if debug: print('debug --- context area is this area') ### DEBUG
        continue
    elif area.x == tgxvalue and area.y == thisarea.y:
        otherarea = area
        if debug: print('debug --- context area is not this area') ### DEBUG
        break
```
the break in it kind of stops the operator if your blender screen has some non text editor area, trying to get the grasp of it !

**Comment by AndreaMonzini** [comment]
If you start Blender from terminal can you please report the terminal messages?
To run quickly the first time Blender from terminal i just drag and drop Blender executable in the terminal in my distro.
Can you also make maybe a GIF video?
Thank you.

**Comment by samytichadou** [comment]
i am running from terminal, but so far no error raised. if i understand correctly, it gets stuck on any non text editor area in the context screen and return finished because of the join operator. I may have a workaround, i'll post it here if it works !

**Comment by samytichadou** [comment]
ok i took a different approach, for now the addon was trying to get all areas and guessing which one could be preview to join it (i'm guessing in order to "cancel" dual screen) but it was a clunky way to do it because of the iteration across the areas, so i get rid of this part for now, and the behavior becomes :
- If preview doesn't exist, the area is split and dual screen is setup
- if it exists, nothing happens
For now there is no "cancelling" the dual screen mode, this could be difficult to do properly, because the user can rearrange its workspace before that. I'm looking into it right now !
I'll add that to the [push request](https://github.com/tin2tin/Blender_Screenwriter/pull/11) i made !

**Comment by samytichadou** [comment]
Hey, i'm rewriting the screenwriter dual_screen operator, and trying to reimplement the join, but here's the problem so far : 

- when overriding the context of the join operator, the direction of the join will take the mouse position (which is going to be left of the area most of the time, giving the way we split) so when clicking right away, the merge happens in the wrong way (the text writing area becomes the preview)
- the way we do the override (from previous code) the join operator must have a border to work, which is the left border, so no way to merge with another area in blender (right or top)
- atop of that, if user adds a preview area by simply changing the text block of any text editor to preview, only one of these previews will be taken into account.

Here's a [video of the problem](https://youtu.be/2O2rZShRAyc)

So my thinking on this problem the join option seems to be too clunky, i think the user should just be able to split current area through the dual_screen operator, then join if needed manually. 
After all the manual way is just one click and drag

**Comment by tin2tin** [comment]
Yes, maybe you're right. I discussed it with the coder who changed the behaviour in 2.81. before you could determine which way to join through the API. I pasted it into one of the now closed issues.

Maybe it's better to leave it without the join until it is properly fixed in the API.

**Comment by samytichadou** [comment]
i just made a pull with rewrite operator, tried to clean the code and add a "global" message and variable logic to it.
[the pull request](https://github.com/tin2tin/Blender_Screenwriter/pull/17)
It now iterates through diferrents windows if any to find a previous preview, then create one if doesn't exist

**Comment by tin2tin** [comment]
This has been sol´ved by https://github.com/tin2tin/Blender_Screenwriter/pull/17
