### ISSUE TITLE
overlap of dialog when creating scene strips

### ISSUE THREAD

**Issue by samytichadou** [tin2tin/Blender_Screenwriter#14]
Hi, on linux 19.04 and blender 2.82 (-e5b788bad8bc-linux-glibc217-x86_64), when creating scene strips from the script you put in the latest zip release, i get some overlapping dialog at 01'05"02
![image](https://user-images.githubusercontent.com/26276003/68994219-bee90600-0880-11ea-99d6-a08a89b64b8a.png)
Here's what it gives when putting the first dialog one channel up
I took a look at the script and i don't think it is wanted. Appart from that , this is a great tool sir ! thanks a lot !

**Comment by AndreaMonzini** [comment]
If you look the at the python script ( for what i understand )the duration depends on `characters_pr_minute = 900`.
In details:
```
duration = int(((len(f.original_content)/characters_pr_minute)*60)*fps)
                in_time = int(((f.original_line/lines_pr_minute)*60)*fps)
```
If you make the dialogue shorter ( less character) , it does not overlap.
Anyway it is just an initial development.

**Comment by samytichadou** [comment]
@AndreaMonzini 
yeah of course ! it was not some complaining of any kind just result of early test for me, i didn't know if you guys were aware of this issue ! thanks for the answer

**Comment by AndreaMonzini** [comment]
Actually i am learning Python and i just tried to explain to myself too :)

**Comment by tin2tin** [comment]
That should be an easy fix once the multi-file commit is ready to be patched(missing join).

**Comment by tin2tin** [comment]
I'm not able to reproduce this one. What's your project fps?

**Comment by AndreaMonzini** [comment]
Hi, i can reproduce it, 24 fps :

![overlap](https://user-images.githubusercontent.com/12413409/69148761-5181e300-0ad5-11ea-91e4-09777e829f0c.png)

**Comment by tin2tin** [comment]
Fixed: https://github.com/tin2tin/Blender_Screenwriter/commit/9904d8200d94f647adc96547cb117c02c7717341
