### ISSUE TITLE
scenes_to_strips operator could mess with existing sequencer edit

### ISSUE THREAD

**Issue by samytichadou** [tin2tin/Blender_Screenwriter#15]
This is not a bug, more a kind of feature request. 

It would be great to have a check done before adding strips to sequencer. If there are any strips from before, a warning should be raised and ask if the user want to delete it or cancel the operations, or even pick manually some sequencer channel to put the created strips

And in case the operator was already used, it should check if scenes already exists !

This will be such a great feature to use ! thanks a lot for it !

**Comment by tin2tin** [comment]
Yeah, there properly should be a check if new scenes should be added or if they just should be updated(remove all scenes strips/text strips with scene strip names and add them again). 

Or the cheap, for now workaround, just add to the first empty channel:
This will do it, but I'm waiting for you commit is ready to patch. 
`                # Find empty channel:
                sequences = bpy.context.sequences
                if not sequences:
                    return 1
                channels = [s.channel for s in sequences]
                channels = sorted(list(set(channels)))
                empty_channel = channels[-1] + 1`

**Comment by tin2tin** [comment]
Now it add new strips to the first empty channel. Later on maybe we can look into updating existing strips. 
https://github.com/tin2tin/Blender_Screenwriter/commit/330f4dd938c2ca027c0e19b8c29c14d634de5221
