### ISSUE TITLE
Problem to add camera

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/Blender_Screenwriter#19]
ERROR (wm.operator): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/windowmanager/intern/wm_event_system.c:1462 wm_operator_invoke: invalid operator call 'VIEW3D_OT_add_scene_strip'

**Comment by tin2tin** [comment]
Are you using 2.82 beta?

**Comment by b4zz4** [comment]
I use 2.81

**Comment by tin2tin** [comment]
You should use 2.82 beta for this add-on. I just checked, and Big Fish converts to strips without errors here on 2.82 beta.

**Comment by tin2tin** [comment]
Can you please confirm that it is working for you on 2.82, so I can close this report?

**Comment by b4zz4** [comment]
work thanks
