### ISSUE TITLE
Make timing of scenes more accurate

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/Blender_Screenwriter#21]
Currently the timing is calculated against number of lines, but the length of the lines are not taken into account. This needs to be done for optimal precision.

**Comment by saucissevolante** [comment]
Hi, great tool !
I'm writing short animation series, 3'30, few dialogs, fast action. The 1mn per page ratio does not work for me (I need a 30' per page for 7 pages). I've tried to change the "lines_pr_minute" value in both "Blender_ScreenWriter_Original" and "scene_to_strip" but it does not seem to work when I  create sequences . Any idea ? Maybe it could become an optional value in the UI ?
Thanks,

Michaël

**Comment by gabrielmontagne** [comment]
I was playing with a modified version of the `scenes_to_strips` operator -- needed to not create scenes straight away, plus some other tweaks -- and was getting a bit of inconsistent timing results and things getting out of phase so opted for a simpler heuristic, 
https://github.com/gabrielmontagne/blender-addon-unfurl-fountain/blob/master/__init__.py#L39-L41

For scene lengths I guesstimate a ratio of words per second for actions and dialogues (times a factor, to slow down speech a bit) and add it up plust a tiny margin.  The numbers coming out worked fine for my screenplays.

**Comment by tin2tin** [comment]
Thank you. So I need to have Blender Screenwriter installed and then run your add-on? 
How does you timing fit with the number of pages(one pr. minut) of the Big Fish screenplay which can be downloaded here: https://fountain.io/syntax

**Comment by gabrielmontagne** [comment]
No need to install Blender Screenwriter, no.  I have it installed because it's very cool.  
It's a great idea to us _Big Fish_ as a benchmark.  I tried it and, well, my heuristic was way off.  3 hours for 120 page script.  I'll tweaks some numbers more and see.   But the heuristic is quite linear so I'll see how it feels if I compress it to that length.

**Comment by gabrielmontagne** [comment]
I [tweaked a number](https://github.com/gabrielmontagne/blender-addon-unfurl-fountain/commit/7920b9ec1629045c2c24f8561d8e86a20d0a5d76#diff-743b1adbf37db12e16e01ef62a6f7d72L28)  and _Big Fish_ is now 2:05, which I think it's close enough.  My own 73 page screenplay is now and hour and 9 minutes, which I think is close enough to get a sense of its rhythm and take it from there.

**Comment by tin2tin** [comment]
Cool. If you like, how do you feel about submit this as a patch to Blender Screenwriter including your additional functions(as new function(not replacing the old))?
(Btw. I noticed that the Text Strip makes a forced line break with inserting "+chr(10)+" into the string), and the BBC standard is around 38 characters for each line in a subtitle).

**Comment by gabrielmontagne** [comment]
Will happily prepare a PR with this different time heuristic and the new operator.   Might not have a terrible amount of tiime this next few days, but I'm dropping a ticket on my personal tracker.  Thanks!

**Comment by tin2tin** [comment]
Thank you. That would be great. Your time heuristic could properly replace the existing, which only deals with number of lines, so Big Fish came out as 60 minutes since it has these very long lines. It worked better with that other script example with the hitmen. 

Personally I ran out of steam when trying the add the asset-assigning-to-keywords code. It would be very cool to get that stuff working, but it's too complicated for me to figure out. I tried the VS code fountain add-on, and it doesn't even have the instant preview, as we do. :-)

**Comment by sirdavid32** [comment]
How does one knows how to manipulate the time duration in the VSE? is this possible?
I already know how to write Fountain format, so when I import my script into this addon, in the VSE: how do I adjust timing?

**Comment by tin2tin** [comment]
You'll have to change the code, like Gabriel did in his add-on. I'm still hoping he'll submit a patch to this project with his timings.

**Comment by tin2tin** [comment]
Unfurl fountain add-on has been merged into Blender screenwriter, so hopefully the timings are better now.
