### ISSUE TITLE
PDF export seems broken

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/Blender_Screenwriter#22]
Seems to be related to this:
https://github.com/vilcans/screenplain/issues/53

**Comment by AndreaMonzini** [comment]
Hello,
there is a discussion to integrate the `libharulibrary` http://libharu.org/ in Blender:

https://lists.blender.org/pipermail/bf-committers/2020-December/050808.html

https://developer.blender.org/T83192

Maybe it could be useful for Blender_Screenwriter PDF export too ;

**Comment by tin2tin** [comment]
Thank you. I didn't know about that. Could be nice if they would support exporting text from the text editor too. 

If you're on Linux, can you test if the various modules install successfully, by simply installing the Blender Screenwriter add-on?

**Comment by AndreaMonzini** [comment]
Yes, i just tried to install the last addon version on Blender 2.91 but i see this error :

```
Traceback (most recent call last):
  File "/app/blender/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/linux/.var/app/org.blender.Blender/config/blender/2.91/scripts/addons/Blender_Screenwriter-master/__init__.py", line 13, in <module>
    import bpy, subprocess, pip
ModuleNotFoundError: No module named 'pip'

```

**Comment by tin2tin** [comment]
Ok. Could you reload load it and try again? (I updated a file)

**Comment by AndreaMonzini** [comment]
i installed pip manually with the instructions we tested in the past  and it works:
```
'/home/linux/App/blender-2.91.0-linux64/2.91/python/bin/python3.7m' -m ensurepip
/home/linux/App/blender-2.91.0-linux64/python/bin/python3.7m' -m pip install screenplain[PDF]

```

Now i try to use a clean Blender to check the addon update

**Comment by AndreaMonzini** [comment]
I tried the updated addon with Blender 2.83.9 but Blender crashed

```
linux@pop-os:~$ '/home/linux/App/blender-2.83.9-linux64/blender' 
found bundled python: /home/linux/App/blender-2.83.9-linux64/2.83/python
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr2 = V_CNDMASK_B32_e32 32768, killed $vgpr2, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
reloading addon: Blender_Screenwriter-master 1610634536.7753696 1610634573.4030187 '/home/linux/.config/blender/2.83/scripts/addons/Blender_Screenwriter-master/__init__.py'
Modules Installed () from '/home/linux/Downloads/Blender_Screenwriter-master.zip' into '/home/linux/.config/blender/2.83/scripts/addons'
Aborted (core dumped)
```

**Comment by tin2tin** [comment]
Could you try again? (I've tried something else)

**Comment by AndreaMonzini** [comment]
Now no crash but this error:

```
Traceback (most recent call last):
  File "/home/linux/.config/blender/2.83/scripts/addons/Blender_Screenwriter-master/__init__.py", line 51, in <module>
    import screenplain.parsers.fountain as fountain
ModuleNotFoundError: No module named 'screenplain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linux/App/blender-2.83.9-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/linux/.config/blender/2.83/scripts/addons/Blender_Screenwriter-master/__init__.py", line 53, in <module>
    subprocess.check_call([pybin, '-m', 'pip', 'install', 'screenplain[PDF]'])
  File "/home/linux/App/blender-2.83.9-linux64/2.83/python/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/linux/App/blender-2.83.9-linux64/blender', '-m', 'pip', 'install', 'screenplain[PDF]']' returned non-zero exit status 1
```.

**Comment by tin2tin** [comment]
In the python console in Blender, what does it write when you enter these two separate lines?
```
import sys
print(sys.executable)
```

**Comment by AndreaMonzini** [comment]
![py](https://user-images.githubusercontent.com/12413409/104617033-43a10100-568b-11eb-893f-1e878b4ecfee.png)

**Comment by tin2tin** [comment]
Oh, it is not pointing to the python.exe on linux...

Is it the same on 2.91?

**Comment by tin2tin** [comment]
I've changed it to the previous python.exe location code(this will cause a reminder on 2.91 to update to code).

**Comment by AndreaMonzini** [comment]
2.91:
![py2](https://user-images.githubusercontent.com/12413409/104626234-f0807b80-5695-11eb-9b5d-df5e9c2911fe.png)

**Comment by AndreaMonzini** [comment]
Python folder structure:
![bl](https://user-images.githubusercontent.com/12413409/104626707-7e5c6680-5696-11eb-91d7-23c3fc46b89c.png)

**Comment by tin2tin** [comment]
So how does that version install in 2.91?

(The current version on the repository is using the presumably 2.83 friendly code )

**Comment by AndreaMonzini** [comment]
Both Blender 2.83 and 2.91 seem to work now ! 
( i plan to to more tests on this weekend )

**Comment by tin2tin** [comment]
That's great news. Thank you. Closing all of the pdf related bug reports now.
