### ISSUE TITLE
Auto format character names and scene headings to caps for export 

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/Blender_Screenwriter#23]
Screenplain will format these elements wrong if not in caps.

**Comment by b4zz4** [comment]
Doesn't @characterName work for you to recognize the character?

**Comment by tin2tin** [comment]
Yes, it should properly be simple to implement. It could be part of a "clean up" function, to make the raw text more fountain export friendly. 

I don't have much time, so if you want to help out with a patch, go ahead. :-)
