### ISSUE TITLE
Errors due to updates in Blender

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/Blender_Screenwriter#25]
Blender 2.93 (Arch Linux)

On Press the button "Generate Screen & Strips":

![2021-06-14_17-36_05](https://user-images.githubusercontent.com/643833/121957205-77667c80-cd38-11eb-9f46-becc4e3da072.png)

**Comment by tin2tin** [comment]
I don't have time to check right now, but maybe it'll work if you add a camera in the 3d scene?

**Comment by b4zz4** [comment]
When rebooting, it's solved. I'm sorry.

**Comment by b4zz4** [comment]
This happens when you choose the 2D editing mode

**Comment by tin2tin** [comment]
Thank you for letting me know. There is actually a bug which appeared if no cameras has been assigned to a keyword. It should be fixed now. 

Let me know how the Screenwriter works for you.

**Comment by b4zz4** [comment]
Un resultado similar. No funciona hasta crear un sequencer → word 

![2021-06-15_11-10_26](https://user-images.githubusercontent.com/643833/122069062-46835780-cdcb-11eb-8cf7-19392a1c16ee.png)

**Comment by tin2tin** [comment]
Can you explain in a bit more detail?

I can see several things are broken due to Blender updates, ex. the cursor do not update position in the screenplay preview anymore and switch to scene doesn't work anymore too. 

I'll reopen this report.

**Comment by tin2tin** [comment]
`It is also a problem that does not create 2D scenes with a camera, because this would be very practical for storyboard`
It'll only add things to the scenes which are assigned to keywords. Ex. if you use normal script formatting with ext/int, then you should be able to assign a camera to those words and then the camera should be added to each scene.

**Comment by b4zz4** [comment]
What you notice is that you don't copy the material from the main scene. 
It is a detail, in general the addon works.

![2021-06-16_10-23_49](https://user-images.githubusercontent.com/643833/122229556-3d5bbe80-ce8f-11eb-8a98-9228b6ce9b7e.png)

**Comment by tin2tin** [comment]
If you have assigned a word to a 3d object and then hit generate scenes, that object should automatically be added to every scene containing that word... if it still works the way it is supposed to. 

When generating the new scenes, I guess it could copy the properties from the original scene, but only the properties. Maybe it is simple to implement. However it shouldn't be for storyboarding only. 

What properties needs to be copied for the best storyboarding/animatic/previz process?

**Comment by b4zz4** [comment]
I think they should be copied and not affect a 3D world because the same thing happens in 3D everything appears in empty, similar to 2D.

**Comment by b4zz4** [comment]
OT: I will join a tutorial in Spanish.
https://fediverse.tv/videos/watch/a99d00a1-1aea-49f9-b4b8-d058d55a6fd1

**Comment by tin2tin** [comment]
Nice to see it in use. Thank you. I actually didn't know about anyone using it, which is properly what I'm a bit reluctant to keep developing it.

**Comment by b4zz4** [comment]
I dreamed of creating something similar, but I really don't have the knowledge to do it, I'm putting up an "open serie" and I think this is going to solve many problems.

https://fediverse.tv/videos/watch/594d6d95-af52-47f1-b423-2a14eb2b4e48


One of the drafts that I'm about to get the tease using this add-on

**Comment by tin2tin** [comment]
Thank you for all of your contributions to this, in the Blender community, forgotten project. I've set up Discussions here on github. So I'll close this thread for now. 

There are some things which needs discussion. Ex.:
- What should Screenwriter do when you generate a new sequence, but already have generated strips in the sequence?

**Comment by b4zz4** [comment]
For nothing, I've been anxious for using this in my project for a long time.
It works really well now.

**Comment by tin2tin** [comment]
Also when generating a new sequence on top of an existing sequence?

**Comment by b4zz4** [comment]
I'd like to improve that, but I don't really know how to do it.
It would be great if you didn't until you could work directly with the script and regenerate the cameras and sequences without touching the timeline in the preproduction

**Comment by tin2tin** [comment]
Here's the discussion on the add-on on github: https://github.com/tin2tin/Blender_Screenwriter/discussions
