### ISSUE TITLE
PDF export does not format correctly

### ISSUE THREAD

**Issue by tushantin** [tin2tin/Blender_Screenwriter#46]
The addon seems to have issues formatting when exporting to PDF. I'm using the Git version of the addon, with Blender 2.93.0. 

EDIT: I tried it with HTML export too, and it's the same issue. 

![image](https://user-images.githubusercontent.com/5314015/139350813-8377d358-fe92-4c26-805a-7cc6f4900087.png)

**Comment by tin2tin** [comment]
You're exporting from the Preview area and not the Edit area.
