### ISSUE TITLE
Cameras in one scene

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/Blender_Screenwriter#47]
Create all the cameras in one scene.

Blender 3.2

![2022-07-04_17-34_02](https://user-images.githubusercontent.com/643833/177214726-8a277220-eb42-4089-b642-8d8242f128d6.jpg)
2

**Comment by tin2tin** [comment]
Could you please explain what the problem is, how to repoduce it and what you'd expect happening instead? (for both this report and your next report)

**Comment by b4zz4** [comment]
I'm sorry. 
By generating the movie, the script creates cameras by scene, but all cameras in one scene.
Looks like an error when the scenes don't have a camera.
