### ISSUE TITLE
error generating mindmap

### ISSUE THREAD

**Issue by kotaxyz** [tin2tin/Blender_Screenwriter#57]
hello there ,thanks alot dev for this awesome tool
i have a problem when i generate mindmap i get this error

Python: RuntimeError: class SCREENWRITER_OT_mindmap_fountain, function execute: incompatible return value , , Function.result expected a set, not a NoneType

note that im using blender 3.3

**Comment by tin2tin** [comment]
Did you install the MindMapper add-on?

**Comment by tin2tin** [comment]
Ok, try now. 

Select the Mind Map in the Editor Selector:
![image](https://user-images.githubusercontent.com/1322593/235343792-5b3073be-f8df-4a6d-a852-214a6c4ff976.png)

**Comment by tin2tin** [comment]
Good it works for you. That thing about subtitles(I only got a mail about it - but it is not visible here?). Hold ALT while changing the size value, and all selected strips should have that value changed too.

**Comment by tin2tin** [comment]
@kotaxyz Let me know how it goes for you. And what kind of workflow you're using it for.

**Comment by tin2tin** [comment]
Holding ALT and "copy value to selected" is the same thing. My Subtitle Editor add-on also have a button to copy all properties from the active strip to the selected strips, including the font, which can't be batch changed by holding ALT or "copy value to selected".

**Comment by tin2tin** [comment]
The subtitle add-on is basically a text strip editor. Maybe I should have called it that instead. https://github.com/tin2tin/Subtitle_Editor
