### ISSUE TITLE
Blender 4 changes

### ISSUE THREAD

**Issue by bazza2jw** [tin2tin/Blender_Screenwriter#58]
To fix exception in dual_view.py when Dual is clicked, make the following changes at lines 62 and 80

Change:
bpy.ops.screen.region_flip(c) 

To:
with context.temp_override(**c):
        bpy.ops.screen.region_flip() 

This is a result of changes to the Blender API.

**Comment by tin2tin** [comment]
Thanks. I couldn't get that to work. But did something else.
